version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "packages/antd"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "packages/core"
    schedule:
      interval: "daily"

  - package-ecosystem: "npm"
    directory: "packages/fluent-ui"
    schedule:
      interval: "daily"
 
  - package-ecosystem: "npm"
    directory: "packages/playground"
    schedule:
      interval: "daily"
 
  - package-ecosystem: "npm"
    directory: "packages/semantic-ui"
    schedule:
      interval: "daily"
