version: 2

mkdocs:
  configuration: mkdocs.yml

# Optionally build your docs in additional formats such as PDF and ePub
formats: all

python:
  version: 3.7
  install:
    - requirements: requirements.docs.txt
